name: Run SeleniumRestAssuredTesting

on:
  schedule:
    - cron: "0 18 * * *" 
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up JDK 18
      uses: actions/setup-java@v2
      with:
        java-version: '18'

    - name: Build Docker Image
      run: docker build -t SeleniumRestAssuredTesting .

    - name: Run Docker Container
      run: docker run SeleniumRestAssuredTesting
