name: Run SeleniumRestAssuredTesting

on:
  schedule:
    - cron: "50 19 * * *"  
  push:
    branches:
      - dev  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up JDK 18
      uses: actions/setup-java@v3
      with:
        java-version: '18'
        distribution: 'temurin'

    - name: Install Allure CLI
      run: |
        wget -O allure-2.13.9.tgz https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.13.9/allure-commandline-2.13.9.tgz \
        && tar -zxvf allure-2.13.9.tgz -C /opt/ \
        && sudo ln -s /opt/allure-2.13.9/bin/allure /usr/bin/allure \
        && rm allure-2.13.9.tgz

    - name: Build Docker Image
      run: docker build -t seleniumrestassuredtesting . 

    - name: Run Docker Container
      run: |
        docker run -v $(pwd)/target/allure-results:/app/target/allure-results seleniumrestassuredtesting 

    - name: Check Allure Results Directory
      run: ls -la target/allure-results  

    - name: Generate Allure Report
      run: allure generate target/allure-results -o target/site/allure-maven-plugin  

    - name: Upload Allure Report to GitHub Pages
      uses: JamesIves/github-pages-deploy-action@v4.2.0
      with:
        branch: gh-pages  
        folder: target/site/allure-maven-plugin  